first=input("Enter 1st number : ")
second=input("Enter 2nd number : ")
add = int(first)+int(second)
print("The sum is : " + str(add))
add = int(first)-int(second)
print("The diffrence is : " + str(add))
add = int(first)*int(second)
print("The  product is : " + str(add))
add = int(first)/int(second)
print("The division is : " + str(add))
